name: Selcuk Otomatik Guncelleme

on:
  workflow_dispatch:
  schedule:
    - cron: '*/10 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Libs
        run: pip install requests beautifulsoup4 urllib3

      - name: Run Script
        run: python selcuk.py

      - name: Push Changes
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add selcukk.m3u
          # Sadece değişiklik varsa devam et
          if ! git diff --cached --quiet; then
            git commit -m "🔄 Liste Guncellendi"
            git pull --rebase origin main
            git push
          else
            echo "Değişiklik yok, atlanıyor."
          fi
